services:
  mysql:
    image: mysql:8.4.4
    container_name: drinkshop_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Taipei
    ports:
      - "30421:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - drinkshop_network
    

  redis:
    image: redis:7.4.2-alpine
    container_name: drinkshop_redis
    environment:
      TZ: Asia/Taipei
    ports:
      - "30422:6379"
    volumes:
      - ./volumes/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - drinkshop_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  drinkshop_network:
    driver: bridge