services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.demoshop
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.demoshopserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
